### ISSUE TITLE
Allow creating branches and pull requests

### ISSUE THREAD

**Issue by justryanw** [snowflakelinux/snow#12]
I have some fixes on a local branch and would like to open a pull request but it doesn't look like I have permissions to create a branch on the remote. Could you guys consider opening up the repository so others can contribute to the project. Thanks.

**Comment by jakehamilton** [comment]
@justryanw you'll want to make a fork in order to submit a PR.

**Comment by justryanw** [comment]
Ah ok sorry, I wasn't aware that you could do pull requests across repositories
