### ISSUE TITLE
Add snow version

### ISSUE THREAD

**Issue by davidak** [snowflakelinux/snow#3]
The tool should have a command to show it's version.

I suggest `version` to be consistent with the other commands, but also support `--version` for compatibility.

It makes also sense to show the Nix version in a second line.

Currently: 

```
[davidak@gaming:~]$ nix run github:snowflakelinux/snow --version
nix (Nix) 2.8.1

[davidak@gaming:~]$ nix run github:snowflakelinux/snow version
error: The subcommand 'version' wasn't recognized

Usage: snow <COMMAND>

For more information try '--help'
```

**Comment by vlinkz** [comment]
69fcd95388e777f88031af52386121b0d6d3d9e7
```bash
$ snow --version
snow 0.0.2
nix (Nix) 2.11.0
```
